@startuml Diagramme de classe
class Clock {
    hourDisplay : HTMLElement
    hourOffset : number
    minuteOffset : number
    editMode : string
    is24HourFormat : boolean
    mode : 'AM' | 'PM' | null
    container : HTMLElement
    initialHourOffset : number
    static count : number
    rowCapacity : number
    verticalMargin : number

    updateTime() : void
    toggleLight() : void
    toggleEditMode() : void
    increase() : void
    reset() : void
    toggleTimeFormat() : void

    attachEventListeners() : void
    handleButtonClick(buttonClass : string) : void
    setupButtons() : void
    positionButton(buttonClass : string, angleRadians : number, rotation : number) : void
    createClockElement() : HTMLElement
    positionClock() : void
}

@enduml
